<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BizAct150" ignored="0" name="test1" tests="1" failures="1" timestamp="2022-07-04T16:33:30 IST" time="6.433" errors="0">
  <testcase name="validate" time="6.382" classname="com.batch.creation.RawSeg.TC_BC_01">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at com.batch.creation.RawSeg.TC_BC_01.validate(TC_BC_01.java:145)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.batch.BatchFrameworkTestAutomation.main(BatchFrameworkTestAutomation.java:48)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate -->
</testsuite> <!-- test1 -->
